### ISSUE TITLE
Get @phish paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#1]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @phish paid the $7.29 they earned.

-------

@phish, we don't have direct contact info for you. 

Can you please email hack@siv.org or message [me on Signal](https://signal.me/#eu/BoJi_hXAgZij8SBK2mGyEoemAKKgZ7_RYOjAOnkgVYCu8IjJAH5EjblXfQ0U3Cbc) so we can get payment information for you?

**Comment by arianabuilds** [comment]
@phish — following-up on this. To get the prize please email your info via hack@siv.org

**Comment by phish** [comment]
Never mind, you can keep the $7.29

**Comment by dsernst** [comment]
Ok. Thanks for the update. Will note this as a contribution back to future rounds of HACK SIV. 

Thank you
