### ISSUE TITLE
Get @cjackett paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#10]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @cjackett paid the $2,071.03 they earned.

-------

@cjackett, we think we have contact info for you. 

Sent you a direct message to confirm, so we can get payment information for you.

**Comment by cjackett** [comment]
Posting proof as requested that I am the person you messaged directly: b12f71fa16

**Comment by dsernst** [comment]
> Posting proof as requested that I am the person you messaged directly: b12f71fa16

Confirmed! Thanks

**Comment by dsernst** [comment]
Payment sent

**Comment by cjackett** [comment]
Confirming successful transfer of funds:

![Screenshot from 2024-10-01 07-57-19](https://github.com/user-attachments/assets/5616b9d5-5867-462e-8f61-1813302d537d)

Thank you SIV and all the best with your platform!
