### ISSUE TITLE
Get @worldpeaceworker paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#2]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @worldpeaceworker paid the $13.91 they earned.

-------

@worldpeaceworker, we think we have contact info for you. 

Sent you a direct message to confirm, so we can get payment information for you.

**Comment by worldpeaceworker** [comment]
Sorry for the late response.  Please add this back to the project!

**Comment by dsernst** [comment]
Thank you! Very generous of you ❤️ 

Moving forward, when talking about HACK SIV, we can list you as an outside financial contributor.
