### ISSUE TITLE
Get @pmeyerson paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#3]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @pmeyerson paid the $130.41 they earned.

-------

@pmeyerson, we don't think we have direct contact info for you.

Can you please email hack@siv.org or message [me on Signal](https://signal.me/#eu/BoJi_hXAgZij8SBK2mGyEoemAKKgZ7_RYOjAOnkgVYCu8IjJAH5EjblXfQ0U3Cbc) so we can get payment information for you?

**Comment by pmeyerson** [comment]
Posting proof as requested that I am the person you messaged directly: 30fc4cd5db

**Comment by dsernst** [comment]
> Posting proof as requested that I am the person you messaged directly: 30fc4cd5db

Confirmed, thanks!

**Comment by dsernst** [comment]
Payment sent

**Comment by pmeyerson** [comment]
Received, thank you.
