### ISSUE TITLE
Get @pleasework-sh paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#5]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @pleasework-sh paid the $242.14 they earned.

-------

@pleasework-sh, we think we have contact info for you. 

Sent you a direct message to confirm, so we can get payment information for you.

**Comment by pleasework-sh** [comment]
Posting proof as requested that I am the person you messaged: daf1c088b0

**Comment by dsernst** [comment]
Confirmed! Thanks

**Comment by dsernst** [comment]
Payment initiated
