### ISSUE TITLE
Get @anon-person404 paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#8]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @anon-person404 paid the $944.60 they earned.

-------

@anon-person404, we don't have direct contact info for you. 

Can you please email hack@siv.org or message [me on Signal](https://signal.me/#eu/BoJi_hXAgZij8SBK2mGyEoemAKKgZ7_RYOjAOnkgVYCu8IjJAH5EjblXfQ0U3Cbc) so we can get payment information for you?

**Comment by anon-person404** [comment]
Posting proof as requested that I am the person who messaged you directly: 63d41e36fcd

**Comment by dsernst** [comment]
> Posting proof as requested that I am the person who messaged you directly: 63d41e36fcd

Confirmed! Thanks

**Comment by dsernst** [comment]
Payment initiated
