### ISSUE TITLE
Get @GABuras paid

### ISSUE THREAD

**Issue by dsernst** [siv-org/hack.siv.org#9]
### Now that HACK SIV @ DEF CON 2024 [results are finalized](https://github.com/siv-org/siv/issues/236#issuecomment-2297574529), time to get all the participants paid.

This issue is to track getting @GABuras paid the $983.22 they earned.

-------

@GABuras, we think we have contact info for you.

Sent you a direct message to confirm, so we can get payment information for you.

**Comment by GABuras** [comment]
Posting proof as requested that I am the person you messaged directly: a6271b4297

**Comment by dsernst** [comment]
> Posting proof as requested that I am the person you messaged directly: a6271b4297

Confirmed. Thanks

**Comment by dsernst** [comment]
Payment sent
